import type { Metadata } from "next";

import { EditorialPage } from "../components";
import { pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata({
  path: "/terms",
  title: "Terms",
  description:
    "Terms for using the Open Queries extension, website and fan-out service.",
});

export default function TermsPage() {
  return (
    <EditorialPage
      eyebrow="Terms · Effective 9 August 2026"
      title="Use the signal responsibly."
      intro="Open Queries is experimental open-source research infrastructure, not a representation of any provider's internal systems."
    >
      <section>
        <h2>Service</h2>
        <p>
          The extension and website are provided to inspect surfaced web-search
          activity and explore estimated retrieval alternatives. Availability,
          supported interfaces and anonymous quotas may change as providers
          update their products.
        </p>
      </section>
      <section>
        <h2>No hidden-reasoning claim</h2>
        <p>
          Observed means visible in the supported interface. Estimated means
          generated by the documented reconstruction method. You must not
          describe estimated candidates as queries definitively used by OpenAI,
          Anthropic or Google.
        </p>
      </section>
      <section>
        <h2>Acceptable use</h2>
        <p>
          Do not use the service to submit secrets, personal data, unlawful
          content, automated high-volume traffic or attempts to bypass limits.
          Do not use query observations to identify or profile an individual.
        </p>
      </section>
      <section>
        <h2>Open-source license and warranty</h2>
        <p>
          The repository is licensed under AGPL-3.0-or-later. Hosted services
          are provided without warranties to the extent permitted by law. You
          remain responsible for validating any business, SEO or publishing
          decision.
        </p>
      </section>
      <section>
        <h2>Provider independence</h2>
        <p>
          Open Queries is independent and is not endorsed by or affiliated with
          OpenAI, Anthropic or Google. Product and company names identify
          compatibility targets only.
        </p>
      </section>
    </EditorialPage>
  );
}
